### PR TITLE
Merge pull request #1 from FGMEMBERS/master

### PR DESCRIPTION
**Pull request by legoboyvdlp**
Merge changes by it0uchpods

### CODE REVIEW

**Comment by FGDATA** [comment]
thanks a lot Lego :P

Do you mind looking for the audios of A320neo and KC137 by FL2070 and
test+push?

IH-COL

**Comment by legoboyvdlp** [comment]
Well, I just pushed the A320 sounds to the upstream... but I don't have the FGMEMBERS copy cloned atm.

**Comment by FGDATA** [comment]
define upstream

On Wed, May 11, 2016 at 10:06 AM, Jonathan Redpath <notifications@github.com

**Comment by legoboyvdlp** [comment]
GitLab A320neo.

**Comment by FGDATA** [comment]
is that public or something "private"? If its private, since FL2070 offered this publicly, I will do the proper pushing to FGMEMBERS then

**Comment by legoboyvdlp** [comment]
Private, sure, go ahead.

**Pull request merged**
